# Generated by Django 2.2.2 on 2019-07-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='subtotal',
            new_name='shipping_total',
        ),
    ]
